import boto3
import json
import os
from datetime import datetime
from typing import Dict, Optional

class EmailReportService:
    def __init__(self):
        self.ses = boto3.client('ses')
        self.sender_email = os.environ.get('SENDER_EMAIL', 'noreply@hotel-revenue-optimization.com')
    
    def send_report_email(self, recipient_email: str, cc_email: str, report_data: Dict, query_summary: str) -> bool:
        """Send formatted report via SES email"""
        try:
            # Format the report content
            report_content = self._format_report_content(report_data, query_summary)
            
            # Create email message
            subject = f"Hotel Revenue Optimization Report - {datetime.now().strftime('%Y-%m-%d %H:%M')}"
            
            # Send email via SES
            response = self.ses.send_email(
                Source=self.sender_email,
                Destination={
                    'ToAddresses': [recipient_email],
                    'CcAddresses': [cc_email] if cc_email != recipient_email else []
                },
                Message={
                    'Subject': {
                        'Data': subject,
                        'Charset': 'UTF-8'
                    },
                    'Body': {
                        'Text': {
                            'Data': report_content,
                            'Charset': 'UTF-8'
                        },
                        'Html': {
                            'Data': self._format_html_content(report_data, query_summary),
                            'Charset': 'UTF-8'
                        }
                    }
                }
            )
            
            print(f"Email sent successfully. MessageId: {response['MessageId']}")
            return True
            
        except Exception as e:
            print(f"Error sending email report: {e}")
            return False
    
    def _format_report_content(self, report_data: Dict, query_summary: str) -> str:
        """Format report data into readable email content"""
        content = f"""Hotel Revenue Optimization Report
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Query Summary: {query_summary}

Report Details:
{json.dumps(report_data, indent=2)}

---
This report was generated by the Hotel Revenue Optimization system.
"""
        return content
    
    def _format_html_content(self, report_data: Dict, query_summary: str) -> str:
        """Format report data into HTML email content"""
        html_content = f"""
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                .header {{ background-color: #f8f9fa; padding: 20px; border-radius: 5px; margin-bottom: 20px; }}
                .content {{ padding: 20px; }}
                .footer {{ background-color: #e9ecef; padding: 10px; text-align: center; font-size: 12px; }}
                pre {{ background-color: #f8f9fa; padding: 15px; border-radius: 5px; overflow-x: auto; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h2>Hotel Revenue Optimization Report</h2>
                <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            </div>
            
            <div class="content">
                <h3>Query Summary</h3>
                <p>{query_summary}</p>
                
                <h3>Report Details</h3>
                <pre>{json.dumps(report_data, indent=2)}</pre>
            </div>
            
            <div class="footer">
                <p>This report was generated by the Hotel Revenue Optimization system.</p>
            </div>
        </body>
        </html>
        """
        return html_content
Hotel Revenue Optimization Report
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}

Query Summary: {query_summary}

Status: {report_data.get('status', 'Unknown').title()}

Report Details:
{report_data.get('report', 'No detailed report available')}

---
© 2025 Zenith Stays Group
Powered by AWS AI Services by Oak City Legion Group
        """.strip()
        
        return content
