AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for storing Cognito client secret in Secrets Manager'

Parameters:
  AppName:
    Type: String
    Default: hotel-revenue-optimization
    Description: Name of the application
  
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Environment (dev, test, prod)
  
  CognitoUserPoolId:
    Type: String
    Description: ID of the Cognito User Pool
  
  CognitoClientId:
    Type: String
    Description: ID of the Cognito User Pool Client
  
  CognitoClientSecret:
    Type: String
    Description: Client secret for the Cognito User Pool Client
    NoEcho: true

Resources:
  CognitoClientSecretSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: CognitoClientSecret
      Description: !Sub "Client secret for ${AppName}-${Environment} Cognito User Pool Client"
      SecretString: !Sub '{"clientId":"${CognitoClientId}","clientSecret":"${CognitoClientSecret}"}'
      Tags:
        - Key: AppName
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  SecretArn:
    Description: ARN of the secret containing the Cognito client secret
    Value: !Ref CognitoClientSecretSecret
    Export:
      Name: !Sub ${AppName}-${Environment}-CognitoClientSecretArn
